spring:
    application:
        name: marketplace
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: create
            naming:
                strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        properties:
            hibernate:
                current_session_context_class:
                    org.springframework.orm.hibernate4.SpringSessionContext
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/marketplace
        name:
        username: postgres
        password: root
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp

server:
    port: 8080